/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.Controlador;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;

/**
 *
 * @author mmf19
 */
public class Vista extends javax.swing.JFrame{
    
    public Vista() {
        initComponents();
        this.setVisible(true);
        this.panelHistorial.setEnabled(false);
        this.panelHistorial.setVisible(false);
        Image ico = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Recourses/logo.png"));
        this.setTitle("Calculadora");
        this.setIconImage(ico);
        this.setResizable(false);
        
        //fondo
        this.getContentPane().setBackground( new Color(250,250,250));
        panelCalculo.setBackground( new Color(250,250,250));
        panelHistorial.setBackground( new Color(250,250,250));
       //Controlador.disenyo("standard");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        lblNumero = new javax.swing.JLabel();
        lblCalculo = new javax.swing.JLabel();
        panelCalculo = new javax.swing.JPanel();
        btnMasMenos = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnPorcentaje = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btnBorrarTodo = new javax.swing.JButton();
        btnBorrarUno = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnDividir = new javax.swing.JButton();
        btnMultiplicar = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btncoma = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btnIgual = new javax.swing.JButton();
        btnRestar = new javax.swing.JButton();
        btnSumar = new javax.swing.JButton();
        panelHistorial = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableHistorial = new javax.swing.JTable();
        btnBorrarHistorial = new javax.swing.JButton();
        JTKeyListener = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu = new javax.swing.JMenu();
        jMenuSalir = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuDisenyo = new javax.swing.JMenu();
        JMIDisenyoStandard = new javax.swing.JMenuItem();
        JMIDisenyoClaro = new javax.swing.JMenuItem();
        JMIDisenyoOscuro = new javax.swing.JMenuItem();
        JMIDisenyoCreem = new javax.swing.JMenuItem();
        jMenuCalcu = new javax.swing.JMenu();
        jMenuHistorial = new javax.swing.JMenu();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(250, 250, 250));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNumero.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblNumero.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNumero.setText("0");
        getContentPane().add(lblNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 28, 282, 42));

        lblCalculo.setForeground(new java.awt.Color(102, 102, 102));
        lblCalculo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(lblCalculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 6, 268, 20));

        btnMasMenos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnMasMenos.setText("+/-");

        btn7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn7.setText("7");

        btn4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn4.setText("4");

        btn1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn1.setText("1");

        btn0.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn0.setText("0");

        btnPorcentaje.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPorcentaje.setText("%");

        btn8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn8.setText("8");

        btnBorrarTodo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBorrarTodo.setText("C");

        btnBorrarUno.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBorrarUno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recourses/icoBorrar.png"))); // NOI18N

        btn9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn9.setText("9");

        btnDividir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDividir.setText("÷");

        btnMultiplicar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnMultiplicar.setText("x");
        btnMultiplicar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btn6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn6.setText("6");

        btn5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn5.setText("5");

        btn2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn2.setText("2");

        btncoma.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btncoma.setText(",");

        btn3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn3.setText("3");

        btnIgual.setBackground(new java.awt.Color(51, 102, 255));
        btnIgual.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnIgual.setForeground(new java.awt.Color(255, 255, 255));
        btnIgual.setText("=");

        btnRestar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRestar.setText("-");
        btnRestar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnSumar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSumar.setText("+");

        javax.swing.GroupLayout panelCalculoLayout = new javax.swing.GroupLayout(panelCalculo);
        panelCalculo.setLayout(panelCalculoLayout);
        panelCalculoLayout.setHorizontalGroup(
            panelCalculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCalculoLayout.createSequentialGroup()
                .addGroup(panelCalculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCalculoLayout.createSequentialGroup()
                        .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCalculoLayout.createSequentialGroup()
                        .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCalculoLayout.createSequentialGroup()
                        .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btncoma, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSumar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCalculoLayout.createSequentialGroup()
                        .addGroup(panelCalculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCalculoLayout.createSequentialGroup()
                                .addComponent(btnMasMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBorrarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBorrarUno, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelCalculoLayout.createSequentialGroup()
                                .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRestar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(0, 6, Short.MAX_VALUE))
        );
        panelCalculoLayout.setVerticalGroup(
            panelCalculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCalculoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelCalculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCalculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnBorrarUno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnMasMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCalculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBorrarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCalculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCalculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCalculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRestar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCalculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCalculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btncoma, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSumar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCalculoLayout.createSequentialGroup()
                        .addComponent(btnIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        getContentPane().add(panelCalculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 76, -1, 250));

        panelHistorial.setFocusable(false);
        panelHistorial.setPreferredSize(new java.awt.Dimension(292, 245));

        jTableHistorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"15 x 3 =", null},
                {"3 - 3 =", null},
                {"66 - 66 =", null},
                {"45 - 15 =", null},
                {null, null}
            },
            new String [] {
                "Operación", "Resultado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableHistorial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTableHistorial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableHistorialMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableHistorial);
        if (jTableHistorial.getColumnModel().getColumnCount() > 0) {
            jTableHistorial.getColumnModel().getColumn(0).setMinWidth(170);
            jTableHistorial.getColumnModel().getColumn(0).setPreferredWidth(170);
            jTableHistorial.getColumnModel().getColumn(0).setMaxWidth(170);
        }

        btnBorrarHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recourses/icoDelete.png"))); // NOI18N

        javax.swing.GroupLayout panelHistorialLayout = new javax.swing.GroupLayout(panelHistorial);
        panelHistorial.setLayout(panelHistorialLayout);
        panelHistorialLayout.setHorizontalGroup(
            panelHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHistorialLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBorrarHistorial)
                .addContainerGap())
        );
        panelHistorialLayout.setVerticalGroup(
            panelHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHistorialLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBorrarHistorial)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panelHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 80, 292, 245));

        JTKeyListener.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTKeyListenerKeyPressed(evt);
            }
        });
        getContentPane().add(JTKeyListener, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 50, 0, -1));

        jMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recourses/icoMenu.png"))); // NOI18N

        jMenuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recourses/icoSalir.png"))); // NOI18N
        jMenuSalir.setText("Salir");
        jMenu.add(jMenuSalir);
        jMenu.add(jSeparator1);

        jMenuDisenyo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recourses/icoDisenyo.png"))); // NOI18N
        jMenuDisenyo.setText("Diseño");

        JMIDisenyoStandard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recourses/icoStandard.png"))); // NOI18N
        JMIDisenyoStandard.setText("Modo standard");
        jMenuDisenyo.add(JMIDisenyoStandard);

        JMIDisenyoClaro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recourses/icoDisenyoBlanco.png"))); // NOI18N
        JMIDisenyoClaro.setText("Modo claro");
        jMenuDisenyo.add(JMIDisenyoClaro);

        JMIDisenyoOscuro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recourses/icoDisenyoOscuro.png"))); // NOI18N
        JMIDisenyoOscuro.setText("Modo oscuro");
        jMenuDisenyo.add(JMIDisenyoOscuro);

        JMIDisenyoCreem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recourses/icoCrem.png"))); // NOI18N
        JMIDisenyoCreem.setText("Modo crema");
        jMenuDisenyo.add(JMIDisenyoCreem);

        jMenu.add(jMenuDisenyo);

        jMenuBar1.add(jMenu);

        jMenuCalcu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recourses/icoCalcular.png"))); // NOI18N
        jMenuCalcu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuCalcuMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuCalcu);

        jMenuHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recourses/icoHistory.png"))); // NOI18N
        jMenuHistorial.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jMenuHistorial.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jMenuHistorial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuHistorialMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuHistorial);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * oculta el panel de calculo, hace visible el de historial y rellena los datos 
     * @param evt 
     */
    private void jMenuHistorialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuHistorialMouseClicked
        // anyadir datos a la tabla
       
        Controlador.anyadirOperacionesTabla();
        panelCalculo.setVisible(false);
        panelCalculo.setEnabled(false);
        panelHistorial.setVisible(true);
        panelHistorial.setEnabled(true);
        
    }//GEN-LAST:event_jMenuHistorialMouseClicked

    /**
     * Oculta el panel del historial y hace visible el panel de calculos
     * @param evt 
     */
    private void jMenuCalcuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuCalcuMouseClicked
        panelCalculo.setVisible(true);
        panelCalculo.setEnabled(true);
        panelHistorial.setVisible(false);
        panelHistorial.setEnabled(false);
    }//GEN-LAST:event_jMenuCalcuMouseClicked

    /**
     * al hacer click te pone el resutado en el lblnumero para poder usarlo postriormente y hacer operaciones
     * @param evt 
     */
    private void jTableHistorialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableHistorialMouseClicked
       Controlador.cogerDatoDelHistorial();
    }//GEN-LAST:event_jTableHistorialMouseClicked

    /**
     * Detecta los botones del teclado como los botones de la pantalla para que sea mas eficiente
     * @param evt 
     */
    private void JTKeyListenerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTKeyListenerKeyPressed
        
        String i =  String.valueOf(evt.getKeyChar());
        
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            i = "";
        }
        if (evt.getKeyCode() == 8) {
            i = "delete";
        }
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            System.exit(0);
        } 
        
        switch (i) {
            case "1" -> Controlador.meterNumero(1);
            case "2" -> Controlador.meterNumero(2);
            case "3" -> Controlador.meterNumero(3);
            case "4" -> Controlador.meterNumero(4);
            case "5" -> Controlador.meterNumero(5);
            case "6" -> Controlador.meterNumero(6);
            case "7" -> Controlador.meterNumero(7);
            case "8" -> Controlador.meterNumero(8);
            case "9" -> Controlador.meterNumero(9);
            case "0" -> Controlador.meterNumero(0);
            case "+" -> Controlador.hacerOperacion("+");
            case "-" -> Controlador.hacerOperacion("-");
            case "*" -> Controlador.hacerOperacion("x");
            case "/" -> Controlador.hacerOperacion("÷");
            case "" -> Controlador.hacerOperacion(null);
            case "." -> Controlador.meterComa();
            case "delete" -> Controlador.borrar(false);
            
        }
    }//GEN-LAST:event_JTKeyListenerKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem JMIDisenyoClaro;
    public javax.swing.JMenuItem JMIDisenyoCreem;
    public javax.swing.JMenuItem JMIDisenyoOscuro;
    public javax.swing.JMenuItem JMIDisenyoStandard;
    public javax.swing.JTextField JTKeyListener;
    public javax.swing.JButton btn0;
    public javax.swing.JButton btn1;
    public javax.swing.JButton btn2;
    public javax.swing.JButton btn3;
    public javax.swing.JButton btn4;
    public javax.swing.JButton btn5;
    public javax.swing.JButton btn6;
    public javax.swing.JButton btn7;
    public javax.swing.JButton btn8;
    public javax.swing.JButton btn9;
    public javax.swing.JButton btnBorrarHistorial;
    public javax.swing.JButton btnBorrarTodo;
    public javax.swing.JButton btnBorrarUno;
    public javax.swing.JButton btnDividir;
    public javax.swing.JButton btnIgual;
    public javax.swing.JButton btnMasMenos;
    public javax.swing.JButton btnMultiplicar;
    public javax.swing.JButton btnPorcentaje;
    public javax.swing.JButton btnRestar;
    public javax.swing.JButton btnSumar;
    public javax.swing.JButton btncoma;
    private javax.swing.JMenu jMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCalcu;
    private javax.swing.JMenu jMenuDisenyo;
    public javax.swing.JMenu jMenuHistorial;
    public javax.swing.JMenuItem jMenuSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    public javax.swing.JTable jTableHistorial;
    private javax.swing.JTextField jTextField1;
    public javax.swing.JLabel lblCalculo;
    public javax.swing.JLabel lblNumero;
    public javax.swing.JPanel panelCalculo;
    public javax.swing.JPanel panelHistorial;
    // End of variables declaration//GEN-END:variables

}
